SystemOrganization addCategory: #'CCodeGenerator-Core'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Examples'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Interpreter'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Nodes'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Support'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Tests'!
SystemOrganization addCategory: #'CCodeGenerator-Core-Translation to C'!
